package main

import (
	"crypto"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"database/sql"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"math/big"
	"net/http"
	"strings"
	"time"

	"github.com/e6qu/sockerless-cloud/sim"
	uiauth "github.com/e6qu/sockerless-cloud/ui-auth"
)

// The simulator issues every data-plane access token — the OAuth2
// service-account token endpoint, the Security Token Service federated token
// exchange, the GCE metadata server token, and IAM Credentials
// generateAccessToken — from one signing key, and the data-plane bearer
// middleware verifies against that same key. Real Google access tokens are
// opaque strings Google introspects internally; the simulator plays the same
// role with a JWT it issues and verifies itself, so a token the simulator
// minted is the only kind its resource endpoints accept.
//
// The issuer and audience are fixed simulator coordinates: an access token is
// opaque to clients (they present it verbatim as `Authorization: Bearer`), so
// the claim contents are the simulator's own contract between its minters and
// its verifier rather than a wire shape any client inspects. The subject
// carries the minted principal (service-account email or federated workforce
// principal).
const (
	simAccessTokenIssuer   = "https://sockerless-sim.googleapis.com"
	simAccessTokenAudience = "https://sockerless-sim.googleapis.com/"
)

// accessSigner is the process-stable RSA key every access-token minter signs
// with and the data-plane middleware verifies against. It is initialised once
// in buildSimulator via initAccessTokenSigner; a nil accessSigner means the
// simulator was constructed without initialising it, which is a programming
// error rather than a runtime condition.
var accessSigner *accessTokenSigner

type accessTokenSigner struct {
	key   *rsa.PrivateKey
	keyID string
}

// accessTokenSigningKeyRecord is the persisted form of the simulator's
// access-token signing key: the RSA private key as PKCS#1 PEM. Reusing the
// key across restarts keeps pre-restart bearer tokens verifiable and the
// published JWKS `kid` stable, the way a real identity provider's signing key
// outlives any single server process.
type accessTokenSigningKeyRecord struct {
	PrivateKeyPEM string `json:"privateKeyPem"`
}

const accessTokenSigningKeyID = "access-token-signing-key"

// initAccessTokenSigner loads the simulator's access-token signing key from
// the persistence store, generating and persisting it on first boot. Without
// persistence (db nil) the key is process-lifetime, matching the rest of the
// in-memory state. It fails loud: an RSA generation failure or a corrupt
// persisted key aborts startup rather than degrading to an unverifiable token.
func initAccessTokenSigner(db *sql.DB) error {
	if accessSigner != nil {
		return nil
	}
	store := sim.MakeStore[accessTokenSigningKeyRecord](db, "token_signing_keys")
	if rec, ok := store.Get(accessTokenSigningKeyID); ok {
		block, _ := pem.Decode([]byte(rec.PrivateKeyPEM))
		if block == nil {
			return fmt.Errorf("persisted access-token signing key is not PEM")
		}
		key, err := x509.ParsePKCS1PrivateKey(block.Bytes)
		if err != nil {
			return fmt.Errorf("parse persisted access-token signing key: %w", err)
		}
		accessSigner = &accessTokenSigner{key: key, keyID: rsaKeyID(&key.PublicKey)}
		return nil
	}
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return fmt.Errorf("generate simulator access-token signing key: %w", err)
	}
	store.Put(accessTokenSigningKeyID, accessTokenSigningKeyRecord{
		PrivateKeyPEM: string(pem.EncodeToMemory(&pem.Block{
			Type:  "RSA PRIVATE KEY",
			Bytes: x509.MarshalPKCS1PrivateKey(key),
		})),
	})
	accessSigner = &accessTokenSigner{key: key, keyID: rsaKeyID(&key.PublicKey)}
	return nil
}

// rsaKeyID derives a stable key identifier from the public key's DER encoding,
// used as the JWKS `kid` and the JWT header `kid`.
func rsaKeyID(pub *rsa.PublicKey) string {
	der, err := x509.MarshalPKIXPublicKey(pub)
	if err != nil {
		// The key was just generated by initAccessTokenSigner; a marshal
		// failure here is not a recoverable runtime condition.
		panic(fmt.Sprintf("marshal simulator public key: %v", err))
	}
	sum := sha256.Sum256(der)
	return base64.RawURLEncoding.EncodeToString(sum[:16])
}

// signWithAccessKey signs an RS256 JWT with the given claim set using the
// simulator's access-token key, so the data-plane bearer middleware verifies
// it. Every bearer the simulator issues — access tokens and the GCE metadata
// server's identity tokens — flows through here so all share one signing key
// and one JWKS.
func signWithAccessKey(claims map[string]any) string {
	if accessSigner == nil {
		panic("simulator access-token signer not initialised")
	}
	header := map[string]string{"alg": "RS256", "typ": "JWT", "kid": accessSigner.keyID}
	headerJSON, _ := json.Marshal(header)
	claimsJSON, _ := json.Marshal(claims)
	signingInput := base64.RawURLEncoding.EncodeToString(headerJSON) + "." +
		base64.RawURLEncoding.EncodeToString(claimsJSON)
	digest := sha256.Sum256([]byte(signingInput))
	sig, err := rsa.SignPKCS1v15(rand.Reader, accessSigner.key, crypto.SHA256, digest[:])
	if err != nil {
		panic(fmt.Sprintf("sign simulator token: %v", err))
	}
	return signingInput + "." + base64.RawURLEncoding.EncodeToString(sig)
}

// signAccessToken issues an RS256 JWT access token for the given principal,
// signed with the simulator's access-token key. Every data-plane access token
// the simulator mints flows through here.
func signAccessToken(subject string, issuedAt, expiresAt time.Time) string {
	return signWithAccessKey(map[string]any{
		"iss":   simAccessTokenIssuer,
		"aud":   simAccessTokenAudience,
		"sub":   subject,
		"iat":   issuedAt.Unix(),
		"exp":   expiresAt.Unix(),
		"scope": "https://www.googleapis.com/auth/cloud-platform",
	})
}

// signIdentityToken issues the RS256 identity token the GCE metadata server's
// `service-accounts/{sa}/identity` endpoint hands a workload. Real Google
// identity tokens are RS256 JWTs a workload presents as its bearer when
// invoking another Cloud Run / Cloud Functions service (audience = the target
// service URL); the simulator plays the same role. It signs with the same key
// its data-plane middleware verifies against, and names both the
// caller-requested audience (as real GCE does) and the simulator's own
// resource-server audience, so the invoked endpoint accepts the token as a
// valid bearer without dropping the requested-audience claim a real identity
// token carries. The subject/email is the workload service-account email.
func signIdentityToken(subject, audience string, issuedAt, expiresAt time.Time) string {
	return signWithAccessKey(map[string]any{
		"iss":            simAccessTokenIssuer,
		"aud":            []string{audience, simAccessTokenAudience},
		"azp":            subject,
		"sub":            subject,
		"email":          subject,
		"email_verified": true,
		"iat":            issuedAt.Unix(),
		"exp":            expiresAt.Unix(),
	})
}

// signInvokeIDToken issues the RS256 ID token the OAuth2 token endpoint returns
// for a service-account JWT-bearer grant that requested one (a workload minting
// the bearer it will present when invoking a Cloud Run / Cloud Functions
// service). It differs from signIdentityToken — the GCE metadata identity
// bearer — in its `aud` shape: the golang.org/x/oauth2 service-account flow
// decodes the returned id_token with a string-typed `aud` (an array fails its
// jws.Decode), so this token carries the single simulator resource-server
// audience the data-plane bearer middleware verifies, rather than the dual
// [target, simulator] audience the metadata path can carry because that token
// is passed through unparsed. The subject/email is the workload
// service-account email.
func signInvokeIDToken(subject string, issuedAt, expiresAt time.Time) string {
	return signWithAccessKey(map[string]any{
		"iss":            simAccessTokenIssuer,
		"aud":            simAccessTokenAudience,
		"azp":            subject,
		"sub":            subject,
		"email":          subject,
		"email_verified": true,
		"iat":            issuedAt.Unix(),
		"exp":            expiresAt.Unix(),
	})
}

// signServiceAccountIDToken issues the RS256 ID token the IAM Credentials
// `serviceAccounts:generateIdToken` API returns for a service account. Real
// Google returns an RS256 JWT whose single `aud` claim is the caller-requested
// audience (the receiving service's URL) and which carries `email` /
// `email_verified` only when includeEmail is set; the simulator matches that
// shape and signs with the same key its data-plane middleware and JWKS use.
// Unlike signIdentityToken — the workload-invoke bearer, which additionally
// names the simulator's own resource-server audience so the bearer middleware
// accepts it — this token mirrors the impersonation API's faithful
// single-audience wire shape, which callers pre-decode rather than present to
// the middleware.
func signServiceAccountIDToken(subject, audience string, includeEmail bool, issuedAt, expiresAt time.Time) string {
	claims := map[string]any{
		"iss": "https://accounts.google.com",
		"aud": audience,
		"azp": subject,
		"sub": subject,
		"iat": issuedAt.Unix(),
		"exp": expiresAt.Unix(),
	}
	if includeEmail {
		claims["email"] = subject
		claims["email_verified"] = true
	}
	return signWithAccessKey(claims)
}

// accessTokenClaims is the claim set of a simulator-minted access token, as
// returned by verifiedAccessTokenClaims for callers — the bearer middleware
// and the Security Token Service introspection endpoint — that need the
// token's contents after verification.
type accessTokenClaims struct {
	Iss   string `json:"iss"`
	Aud   any    `json:"aud"`
	Sub   string `json:"sub"`
	Scope string `json:"scope"`
	Exp   int64  `json:"exp"`
	Iat   int64  `json:"iat"`
}

// verifyAccessToken checks that a bearer token is one the simulator minted:
// a well-formed RS256 JWT, signed by the simulator's key, carrying the
// simulator's issuer and audience, and unexpired. It returns a descriptive
// error the middleware surfaces in the UNAUTHENTICATED response.
func verifyAccessToken(raw string) error {
	_, err := verifiedAccessTokenClaims(raw)
	return err
}

// verifiedAccessTokenClaims verifies a simulator-minted access token and
// returns its claims: a well-formed RS256 JWT, signed by the simulator's key,
// carrying the simulator's issuer and audience, and unexpired.
func verifiedAccessTokenClaims(raw string) (accessTokenClaims, error) {
	var claims accessTokenClaims
	if accessSigner == nil {
		return claims, fmt.Errorf("access-token signer not initialised")
	}
	parts := strings.Split(raw, ".")
	if len(parts) != 3 {
		return claims, fmt.Errorf("token is not a JWT")
	}
	headerJSON, err := base64.RawURLEncoding.DecodeString(parts[0])
	if err != nil {
		return claims, fmt.Errorf("token header is not base64url: %w", err)
	}
	var header struct {
		Alg string `json:"alg"`
	}
	if err := json.Unmarshal(headerJSON, &header); err != nil {
		return claims, fmt.Errorf("token header is not JSON: %w", err)
	}
	if header.Alg != "RS256" {
		return claims, fmt.Errorf("token algorithm %q is not RS256", header.Alg)
	}

	signingInput := parts[0] + "." + parts[1]
	sig, err := base64.RawURLEncoding.DecodeString(parts[2])
	if err != nil {
		return claims, fmt.Errorf("token signature is not base64url: %w", err)
	}
	digest := sha256.Sum256([]byte(signingInput))
	if err := rsa.VerifyPKCS1v15(&accessSigner.key.PublicKey, crypto.SHA256, digest[:], sig); err != nil {
		return claims, fmt.Errorf("token signature is invalid")
	}

	claimsJSON, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return claims, fmt.Errorf("token claims are not base64url: %w", err)
	}
	if err := json.Unmarshal(claimsJSON, &claims); err != nil {
		return claims, fmt.Errorf("token claims are not JSON: %w", err)
	}
	if claims.Iss != simAccessTokenIssuer {
		return claims, fmt.Errorf("token issuer %q is not recognised", claims.Iss)
	}
	if !audienceContains(claims.Aud, simAccessTokenAudience) {
		return claims, fmt.Errorf("token audience does not include the simulator")
	}
	if claims.Exp == 0 {
		return claims, fmt.Errorf("token has no expiry")
	}
	if time.Now().After(time.Unix(claims.Exp, 0)) {
		return claims, fmt.Errorf("token has expired")
	}
	return claims, nil
}

// audienceContains reports whether the JWT `aud` claim — a string or an array
// of strings per RFC 7519 — includes the wanted audience.
func audienceContains(aud any, want string) bool {
	switch v := aud.(type) {
	case string:
		return v == want
	case []any:
		for _, item := range v {
			if s, ok := item.(string); ok && s == want {
				return true
			}
		}
	}
	return false
}

// registerTokenDiscovery publishes the OpenID Connect discovery document and
// JSON Web Key Set for the simulator's access-token signing key, the way a
// cloud identity provider publishes the keys a resource server verifies its
// tokens against. Both endpoints are unauthenticated (they are the material a
// caller needs before it can present a token) and are exempt from the bearer
// middleware.
func registerTokenDiscovery(srv *sim.Server) {
	srv.HandleFunc("GET /.well-known/openid-configuration", func(w http.ResponseWriter, r *http.Request) {
		issuer := requestOrigin(r)
		sim.WriteJSON(w, http.StatusOK, map[string]any{
			"issuer":                                issuer,
			"jwks_uri":                              issuer + "/.well-known/jwks.json",
			"token_endpoint":                        issuer + "/token",
			"response_types_supported":              []string{"token"},
			"subject_types_supported":               []string{"public"},
			"id_token_signing_alg_values_supported": []string{"RS256"},
		})
	})
	srv.HandleFunc("GET /.well-known/jwks.json", func(w http.ResponseWriter, r *http.Request) {
		if accessSigner == nil {
			GCPError(w, http.StatusInternalServerError, "access-token signer not initialised", "INTERNAL")
			return
		}
		pub := &accessSigner.key.PublicKey
		sim.WriteJSON(w, http.StatusOK, map[string]any{
			"keys": []map[string]string{{
				"kty": "RSA",
				"use": "sig",
				"alg": "RS256",
				"kid": accessSigner.keyID,
				"n":   base64.RawURLEncoding.EncodeToString(pub.N.Bytes()),
				"e":   base64.RawURLEncoding.EncodeToString(big.NewInt(int64(pub.E)).Bytes()),
			}},
		})
	})
}

// requestOrigin reconstructs the scheme://host base URL the request arrived on,
// used as the published OpenID Connect issuer.
func requestOrigin(r *http.Request) string {
	scheme := "http"
	if r.TLS != nil {
		scheme = "https"
	}
	if forwarded := r.Header.Get("X-Forwarded-Proto"); forwarded != "" {
		scheme = forwarded
	}
	return scheme + "://" + r.Host
}

// bearerAuthMiddleware verifies the Authorization: Bearer access token on every
// data-plane request. Real Google APIs reject a request without a valid OAuth2
// access token with HTTP 401 UNAUTHENTICATED; the simulator does the same,
// verifying the token against the key it issued it with. Endpoints that a real
// Google client reaches without a bearer — the token minters, OpenID Connect
// discovery and JWKS, the health check, the GCE metadata server (gated by the
// Metadata-Flavor header instead), the console and its own authentication
// layer, and the OCI registry data plane (its own registry-token/Basic scheme)
// — are exempt.
//
// A URI no method publishes is answered before the credential is examined, the
// way Google's own API frontend does: `GET https://run.googleapis.com/nope`
// answers 404 anonymously while `GET .../v2/projects/…/services` answers 401.
// Authenticating first would make every unrouted path answer 401 and turn the
// absence of a route into an authentication failure, hiding both from a
// client — the simulator would report an endpoint it does not serve as one
// that merely rejected the caller.
func bearerAuthMiddleware(srv *sim.Server) func(http.Handler) http.Handler {
	mux := srv.Mux()
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if isAuthExempt(r) || !publishesAPIMethod(mux, r) {
				next.ServeHTTP(w, r)
				return
			}
			if !verifyRequestBearer(w, r) {
				return
			}
			next.ServeHTTP(w, r)
		})
	}
}

// verifyRequestBearer checks the request's OAuth2 access token against the key
// the simulator issued it with, writing Google's UNAUTHENTICATED response and
// reporting false when it is missing or unverifiable. A host-addressed data
// plane that the API-method gate does not cover calls it itself, once it knows
// the request is one it serves.
func verifyRequestBearer(w http.ResponseWriter, r *http.Request) bool {
	auth := r.Header.Get("Authorization")
	const prefix = "Bearer "
	if !strings.HasPrefix(auth, prefix) {
		GCPError(w, http.StatusUnauthorized,
			"Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential.",
			"UNAUTHENTICATED")
		return false
	}
	if err := verifyAccessToken(strings.TrimSpace(auth[len(prefix):])); err != nil {
		GCPError(w, http.StatusUnauthorized,
			"Invalid authentication credentials: "+err.Error(),
			"UNAUTHENTICATED")
		return false
	}
	return true
}

// gcpDataPlaneCatchAlls are the mount patterns of the simulator's
// host-addressed data planes: the Compute Engine load-balancer front end,
// which claims every path on a forwarding rule's address, and the Cloud
// Storage XML data plane, which claims every path whose first segment is a
// bucket. They match any URI, so a match on one is not evidence that a Google
// API method publishes it — the handler behind each decides from the Host or
// the bucket, and does its own authentication once it has.
var gcpDataPlaneCatchAlls = map[string]bool{
	"/{path...}":            true,
	"/{bucket}/{object...}": true,
}

// publishesAPIMethod reports whether a Google API method claims the request.
// Go's ServeMux answers an unmatched request with its own not-found handler and
// an empty pattern; a matched one names the pattern that will serve it.
func publishesAPIMethod(mux *http.ServeMux, r *http.Request) bool {
	_, pattern := mux.Handler(r)
	return pattern != "" && !gcpDataPlaneCatchAlls[pattern]
}

// isAuthExempt reports whether a request reaches a surface a real Google client
// contacts without an OAuth2 access token. Everything else is data plane and
// requires a verified bearer.
func isAuthExempt(r *http.Request) bool {
	p := r.URL.Path
	switch {
	case p == "/health":
		return true
	case p == "/":
		return true
	case r.Method == http.MethodPost && (p == "/token" || p == "/oauth2/v4/token" || p == "/o/oauth2/token" || p == "/v1/token"):
		// Token minters: how a client obtains a token in the first place.
		return true
	case r.Method == http.MethodPost && p == "/v1/introspect":
		// Security Token Service token introspection authenticates with
		// OAuth client credentials (RFC 7662 §2.1) inside the handler — a
		// client introspects the very token it would otherwise present.
		return true
	case strings.HasPrefix(p, "/.well-known/"):
		// OpenID Connect discovery + JWKS.
		return true
	case strings.HasPrefix(p, "/computeMetadata/"):
		// GCE metadata server — gated by the Metadata-Flavor: Google header
		// inside the handlers, not by a bearer (matches real GCE).
		return true
	case strings.HasPrefix(p, "/ui/") || strings.HasPrefix(p, "/auth/"):
		// The console SPA and its own OpenID Connect authentication layer,
		// which use a server-side session, not a cloud access token.
		return true
	case p == uiauth.MonitoringPath:
		// Application monitoring has its own deployment-provided bearer. Its
		// handler validates that credential; treating it as a Google access
		// token prevents the handler from ever seeing a valid request.
		return true
	case isOCIRegistryPath(p):
		// The OCI Distribution data plane authenticates with its own
		// registry-token / Basic scheme, distinct from the cloud bearer.
		return true
	}
	return false
}

// isOCIRegistryPath reports whether a /v2/ path is served by the OCI
// Distribution registry rather than a Google control-plane API. Most of the
// simulator's /v2/ surface is real Google data plane (Cloud Run, Cloud
// Functions v2, Bigtable admin, Cloud Logging) under /v2/projects/... or
// /v2/entries...; only registry blob/manifest/tag traffic, the base endpoint
// and the Docker token service belong to the OCI registry. This mirrors the
// dispatch in the shared OCI registry's serve method, including its skip of
// /v2/projects/.
func isOCIRegistryPath(p string) bool {
	if p == "/v2" || p == "/v2/" || p == arTokenPath {
		return true
	}
	if !strings.HasPrefix(p, "/v2/") || strings.HasPrefix(p, "/v2/projects/") {
		return false
	}
	rest := strings.TrimPrefix(p, "/v2/")
	return strings.Contains(rest, "/blobs/") ||
		strings.Contains(rest, "/manifests/") ||
		strings.HasSuffix(rest, "/tags/list")
}
