package main

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"net/http"
	"net/url"
	"strings"
)

// Authentication for the Azure Cosmos DB data plane.
//
// Every data-plane request carries an `Authorization` header holding a token
// the client builds from one of the account's keys, documented in "Access
// control on Azure Cosmos DB resources"
// (learn.microsoft.com/rest/api/cosmos-db/access-control-on-cosmosdb-resources).
// The header's format is
//
//	type={typeoftoken}&ver={tokenversion}&sig={hashsignature}
//
// URL-encoded as a whole, and for a shared-key ("master") token the signature
// is the base64 HMAC-SHA256, under the base64-decoded account key, of
//
//	"{verb}\n{resourceType}\n{resourceLink}\n{date}\n\n"
//
// — "note the extra new line at the end of the payload". The verb, the
// resource type and the date are lowercased; the resource link is not, because
// "the resource names that are being referenced as part of the ResourceLink
// value are case sensitive and must match the casing of how they were declared
// in the database", while "the other components must be lowercase". The date
// is the request's `x-ms-date`, "the date of the request per RFC 1123 date
// format expressed in Coordinated Universal Time".
//
// The resource type is the kind of resource the request addresses — `dbs`,
// `colls`, `docs`, `sprocs`, `udfs`, `triggers`, `users`, `permissions`,
// `pkranges`, `offers`, `conflicts` — and the resource link is "the identity
// property of the resource that the request is directed at": the resource's own
// link for an operation on one resource, and "the link of the parent resource"
// for a List, Create or Query over a set of them, which is the empty string
// when the parent is the account itself.
//
// An account has four keys — primaryMasterKey, secondaryMasterKey,
// primaryReadonlyMasterKey and secondaryReadonlyMasterKey. All four
// authenticate a read; only the two read-write keys authenticate a write,
// which is why "using read-only keys for write operations" is one of the
// documented causes of the 401 this returns
// (learn.microsoft.com/azure/cosmos-db/troubleshoot-unauthorized). A key is
// verified by value, exactly as the service does it: the read-only keys are
// simply different secrets, so a write signed with one does not verify against
// the read-write pair. Both slots of a pair are live at once, which is what
// makes the documented key rotation — move traffic to the secondary key, then
// regenerate the primary — possible at all.
//
// Resource tokens (`type=resource`) are a separate credential, minted by an
// intermediate server from a permission resource. Microsoft publishes the
// token's shape but not the algorithm that constructs its signature ("Resource
// tokens must be generated by an intermediate server"), so this simulator
// cannot verify one and refuses it rather than accepting it unchecked.
// Microsoft Entra tokens (`type=aad`, the Cosmos DB role-based access control
// credential) are refused for the same reason: the account's role assignments
// they are checked against are not modelled here.

// cosmosMasterKeyRoles are the account key roles, in the order listKeys serves
// them, paired with whether the role may authorize a write.
var cosmosMasterKeyRoles = []struct {
	role     string
	writable bool
}{
	{"primary", true},
	{"secondary", true},
	{"primary-readonly", false},
	{"secondary-readonly", false},
}

// cosmosResourceSegments are the collection path segments a Cosmos resource
// link is built from. A path whose last segment is one of these addresses the
// set rather than a member of it, which is what decides whether the resource
// link is the addressed resource or its parent.
var cosmosResourceSegments = map[string]bool{
	"dbs":                  true,
	"colls":                true,
	"docs":                 true,
	"sprocs":               true,
	"udfs":                 true,
	"triggers":             true,
	"users":                true,
	"permissions":          true,
	"pkranges":             true,
	"offers":               true,
	"conflicts":            true,
	"clientencryptionkeys": true,
	"attachments":          true,
}

// CosmosDataPlaneAuthMiddleware enforces the Cosmos DB data plane's own
// authorization on every request that reaches it. It runs as a middleware
// rather than per handler so a data-plane route cannot be added without it.
func CosmosDataPlaneAuthMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !cosmosIsDataPlanePath(r.URL.Path) {
			next.ServeHTTP(w, r)
			return
		}
		if !cosmosAuthorizeDataPlane(w, r) {
			return
		}
		next.ServeHTTP(w, r)
	})
}

// cosmosIsDataPlanePath reports whether a path addresses the Cosmos data plane.
// The account root is excluded here and authorized by the handler that owns it,
// because the simulator serves its operator console on the same path and only
// the handler can tell the two apart.
func cosmosIsDataPlanePath(requestPath string) bool {
	for _, prefix := range []string{"/dbs", "/offers"} {
		if requestPath == prefix || strings.HasPrefix(requestPath, prefix+"/") {
			return true
		}
	}
	return false
}

// cosmosAuthorizeDataPlane verifies the request's shared-key authorization
// against the addressed account's keys, writing the service's 401 and
// reporting false when it does not authorize.
func cosmosAuthorizeDataPlane(w http.ResponseWriter, r *http.Request) bool {
	header := strings.TrimSpace(r.Header.Get("Authorization"))
	if header == "" {
		cosmosUnauthorized(w, "The authorization header was not set. Every request must carry an Authorization header and an x-ms-date header.")
		return false
	}
	tokenType, version, signature := cosmosParseAuthorization(header)
	switch tokenType {
	case "master":
	case "resource":
		cosmosUnauthorized(w, "Resource tokens are issued by an intermediate server holding the account's master key and are not accepted here. Use a master key.")
		return false
	case "aad":
		cosmosUnauthorized(w, "Azure Cosmos DB role-based access control tokens are not accepted here. Use a master key.")
		return false
	default:
		cosmosUnauthorized(w, "The authorization token is not well formed. It must read type=master&ver=1.0&sig=<signature>.")
		return false
	}
	if version != "1.0" || signature == "" {
		cosmosUnauthorized(w, "The authorization token is not well formed. It must read type=master&ver=1.0&sig=<signature>.")
		return false
	}
	date := strings.TrimSpace(r.Header.Get("x-ms-date"))
	if date == "" {
		cosmosUnauthorized(w, "The authorization header was not set. Every request must carry an Authorization header and an x-ms-date header.")
		return false
	}

	resourceType, resourceLink := cosmosSignedResource(r.URL.Path)
	stringToSign := cosmosStringToSign(r.Method, resourceType, resourceLink, date)

	accountID, ok := cosmosDataAccountID(r)
	if !ok {
		cosmosUnauthorized(w, cosmosSignatureMismatchMessage(stringToSign))
		return false
	}
	write := !cosmosIsReadOperation(r)
	for _, key := range cosmosMasterKeyRoles {
		if write && !key.writable {
			continue
		}
		material, err := base64.StdEncoding.DecodeString(cosmosKeyMaterial(accountID, key.role))
		if err != nil {
			continue
		}
		mac := hmac.New(sha256.New, material)
		_, _ = mac.Write([]byte(stringToSign))
		if hmac.Equal([]byte(signature), []byte(base64.StdEncoding.EncodeToString(mac.Sum(nil)))) {
			return true
		}
	}
	cosmosUnauthorized(w, cosmosSignatureMismatchMessage(stringToSign))
	return false
}

// cosmosParseAuthorization decodes an Authorization header and splits out its
// three fields. The whole token is URL-encoded by the clients that build it —
// the Go SDK with url.QueryEscape, the documented C# sample with
// WebUtility.UrlEncode — so it is percent-decoded here; a `+` is left alone,
// because a base64 signature carries them and no field of the token can hold a
// space for one to stand in for.
func cosmosParseAuthorization(header string) (tokenType, version, signature string) {
	decoded, err := url.PathUnescape(header)
	if err != nil {
		decoded = header
	}
	for _, field := range strings.Split(decoded, "&") {
		name, value, found := strings.Cut(field, "=")
		if !found {
			continue
		}
		switch strings.ToLower(strings.TrimSpace(name)) {
		case "type":
			tokenType = strings.ToLower(strings.TrimSpace(value))
		case "ver":
			version = strings.TrimSpace(value)
		case "sig":
			signature = strings.TrimSpace(value)
		}
	}
	return tokenType, version, signature
}

// cosmosStringToSign builds the payload a shared-key signature covers:
// "{verb}\n{resourceType}\n{resourceLink}\n{date}\n\n", with the verb, the
// resource type and the date lowercased and the resource link left in the
// casing the resources were declared with.
func cosmosStringToSign(method, resourceType, resourceLink, date string) string {
	return strings.ToLower(method) + "\n" +
		strings.ToLower(resourceType) + "\n" +
		resourceLink + "\n" +
		strings.ToLower(date) + "\n" +
		"" + "\n"
}

// cosmosSignedResource derives the resource type and resource link a request's
// signature covers from its path. A path ending in a collection segment
// addresses the set — a list, a create or a query — so its link is the parent
// the set hangs off; any other path addresses one resource, whose link is the
// path itself and whose type is the segment the resource is a member of.
func cosmosSignedResource(requestPath string) (resourceType, resourceLink string) {
	segments := strings.Split(strings.Trim(requestPath, "/"), "/")
	if len(segments) == 1 && segments[0] == "" {
		return "", ""
	}
	// Offers are the documented exception to both halves of the rule: "the
	// ResourceType should be \"offers\"[, the] ResourceLink should be *only*
	// the _rid of the offer you wish to retrieve[, and] the value must be
	// lowercase" (Get an Offer). Every other resource link is the path and
	// keeps the casing its resources were declared with.
	if strings.EqualFold(segments[0], "offers") {
		if len(segments) == 1 {
			return "offers", ""
		}
		return "offers", strings.ToLower(segments[1])
	}
	last := segments[len(segments)-1]
	if cosmosResourceSegments[strings.ToLower(last)] {
		return last, strings.Join(segments[:len(segments)-1], "/")
	}
	if len(segments) >= 2 {
		resourceType = segments[len(segments)-2]
	}
	return resourceType, strings.Join(segments, "/")
}

// cosmosIsReadOperation reports whether a request only reads. A query is a POST
// that carries the `x-ms-documentdb-isquery` header, and reads like any other
// read; every other POST, and every PUT, PATCH and DELETE, writes.
func cosmosIsReadOperation(r *http.Request) bool {
	switch r.Method {
	case http.MethodGet, http.MethodHead:
		return true
	case http.MethodPost:
		if strings.EqualFold(strings.TrimSpace(r.Header.Get("x-ms-documentdb-isquery")), "true") {
			return true
		}
		return strings.HasPrefix(r.Header.Get("Content-Type"), "application/query+json")
	default:
		return false
	}
}

// cosmosDataAccountID resolves the ARM resource identifier of the account whose
// endpoint a data-plane request addressed, which is the account whose keys sign
// it.
func cosmosDataAccountID(r *http.Request) (string, bool) {
	name := cosmosDataAccount(r)
	// An account name is a hostname in Azure and therefore unique, so at most
	// one record answers for it. The lowest identifier is taken when several
	// do, so a request resolves to the same account — and therefore the same
	// keys — every time.
	resolved := ""
	for _, account := range cosmosAccounts.List() {
		if account.Name == name && (resolved == "" || account.ID < resolved) {
			resolved = account.ID
		}
	}
	return resolved, resolved != ""
}

// cosmosSignatureMismatchMessage is the message the service returns when a
// signature does not verify. It echoes the string the server signed, as the
// service does, so a client that built the payload differently can see how.
func cosmosSignatureMismatchMessage(stringToSign string) string {
	return "The MAC signature found in the HTTP request is not the same as the computed signature. Server used following string to sign - '" +
		strings.ReplaceAll(stringToSign, "\n", `\n`) +
		"'. Learn more: https://aka.ms/cosmosdb-tsg-mac-signature"
}

// cosmosUnauthorized writes the data plane's 401.
func cosmosUnauthorized(w http.ResponseWriter, message string) {
	cosmosDataError(w, "Unauthorized", message, http.StatusUnauthorized)
}
