package main

import (
	"fmt"
	"net/http"
	"sort"
	"strings"

	"github.com/e6qu/sockerless-cloud/sim"
)

type PrivateDnsZone struct {
	ID         string            `json:"id"`
	Name       string            `json:"name"`
	Type       string            `json:"type"`
	Location   string            `json:"location"`
	Etag       string            `json:"etag,omitempty"`
	Tags       map[string]string `json:"tags,omitempty"`
	Properties DnsZoneProperties `json:"properties"`
}

type DnsZoneProperties struct {
	MaxNumberOfRecordSets                 int    `json:"maxNumberOfRecordSets"`
	NumberOfRecordSets                    int    `json:"numberOfRecordSets"`
	MaxNumberOfVirtualNetworkLinks        int    `json:"maxNumberOfVirtualNetworkLinks"`
	NumberOfVirtualNetworkLinks           int    `json:"numberOfVirtualNetworkLinks"`
	MaxNumberOfVirtualNetworkLinksWithReg int    `json:"maxNumberOfVirtualNetworkLinksWithRegistration"`
	NumberOfVirtualNetworkLinksWithReg    int    `json:"numberOfVirtualNetworkLinksWithRegistration"`
	ProvisioningState                     string `json:"provisioningState"`
}

type RecordSet struct {
	ID         string              `json:"id"`
	Name       string              `json:"name"`
	Type       string              `json:"type"`
	Etag       string              `json:"etag,omitempty"`
	Properties RecordSetProperties `json:"properties"`
}

// RecordSetProperties holds the properties of a DNS record set. Real
// Azure Private DNS supports A/AAAA/CNAME/MX/PTR/SOA/SRV/TXT records;
// terraform-provider-azurerm's `azurerm_private_dns_*_record` and the
// SDK's `armprivatedns.NewRecordSetsClient` round-trip every shape.
// Service discovery reaches a cloud app through a CNAME alias to its FQDN, so
// the record type has to be served rather than 501.
type RecordSetProperties struct {
	TTL              int               `json:"ttl,omitempty"`
	Fqdn             string            `json:"fqdn,omitempty"`
	IsAutoRegistered bool              `json:"isAutoRegistered"`
	ARecords         []ARecord         `json:"aRecords,omitempty"`
	AAAARecords      []AAAARecord      `json:"aaaaRecords,omitempty"`
	CNAMERecord      *CNAMERecord      `json:"cnameRecord,omitempty"`
	MXRecords        []MXRecord        `json:"mxRecords,omitempty"`
	PTRRecords       []PTRRecord       `json:"ptrRecords,omitempty"`
	SRVRecords       []SRVRecord       `json:"srvRecords,omitempty"`
	TXTRecords       []TXTRecord       `json:"txtRecords,omitempty"`
	SOARecord        *SOARecord        `json:"soaRecord,omitempty"`
	Metadata         map[string]string `json:"metadata,omitempty"`
}

type ARecord struct {
	IPv4Address string `json:"ipv4Address"`
}

type AAAARecord struct {
	IPv6Address string `json:"ipv6Address"`
}

// CNAMERecord represents a CNAME record. RFC restricts a name to one
// CNAME, so this is a singleton (not a slice) per the real ARM shape.
type CNAMERecord struct {
	CName string `json:"cname"`
}

type MXRecord struct {
	Preference int32  `json:"preference"`
	Exchange   string `json:"exchange"`
}

type PTRRecord struct {
	PTRDName string `json:"ptrdname"`
}

type SRVRecord struct {
	Priority int32  `json:"priority"`
	Weight   int32  `json:"weight"`
	Port     int32  `json:"port"`
	Target   string `json:"target"`
}

// TXTRecord represents a TXT record. `Value` is the slice of strings
// composing the record body — real Azure encodes long TXT values as
// multiple chunks ≤255 bytes per the DNS RFC.
type TXTRecord struct {
	Value []string `json:"value"`
}

// SOARecord represents a SOA record (autogenerated for new zones).
type SOARecord struct {
	Host         string `json:"host,omitempty"`
	Email        string `json:"email,omitempty"`
	SerialNumber int64  `json:"serialNumber,omitempty"`
	RefreshTime  int32  `json:"refreshTime,omitempty"`
	RetryTime    int32  `json:"retryTime,omitempty"`
	ExpireTime   int32  `json:"expireTime,omitempty"`
	MinimumTTL   int32  `json:"minimumTtl,omitempty"`
}

// VNetLink represents a Virtual Network Link to a Private DNS Zone.
type VNetLink struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Type       string             `json:"type"`
	Location   string             `json:"location"`
	Tags       map[string]string  `json:"tags,omitempty"`
	Properties VNetLinkProperties `json:"properties"`
}

type VNetLinkProperties struct {
	VirtualNetwork          *VNetLinkVNet `json:"virtualNetwork,omitempty"`
	RegistrationEnabled     bool          `json:"registrationEnabled"`
	VirtualNetworkLinkState string        `json:"virtualNetworkLinkState"`
	ProvisioningState       string        `json:"provisioningState"`
}

type VNetLinkVNet struct {
	ID string `json:"id"`
}

var (
	azurePrivateDNSZones      sim.Store[PrivateDnsZone]
	azurePrivateDNSRecordSets sim.Store[RecordSet]
	azurePrivateDNSVNetLinks  sim.Store[VNetLink]
)

func registerPrivateDNS(srv *sim.Server) {
	zones := sim.MakeStore[PrivateDnsZone](srv.DB(), "dns_zones")
	recordSets := sim.MakeStore[RecordSet](srv.DB(), "dns_record_sets")
	azurePrivateDNSZones = zones
	azurePrivateDNSRecordSets = recordSets

	const armBase = "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network"

	// PUT - Create or update zone
	srv.HandleFunc("PUT "+armBase+"/privateDnsZones/{zoneName}", func(w http.ResponseWriter, r *http.Request) {
		sub := sim.PathParam(r, "subscriptionId")
		rg := sim.PathParam(r, "resourceGroupName")
		zoneName := sim.PathParam(r, "zoneName")

		var req PrivateDnsZone
		if err := sim.ReadJSON(r, &req); err != nil {
			AzureError(w, "InvalidRequestContent", "Failed to parse request body: "+err.Error(), http.StatusBadRequest)
			return
		}

		location := req.Location
		if location == "" {
			location = "global"
		}

		resourceID := fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s",
			sub, rg, zoneName)

		_, exists := zones.Get(resourceID)

		zone := PrivateDnsZone{
			ID:       resourceID,
			Name:     zoneName,
			Type:     "Microsoft.Network/privateDnsZones",
			Location: strings.ToLower(location),
			Etag:     generateUUID(),
			Tags:     req.Tags,
			Properties: DnsZoneProperties{
				MaxNumberOfRecordSets:                 25000,
				NumberOfRecordSets:                    0,
				MaxNumberOfVirtualNetworkLinks:        1000,
				NumberOfVirtualNetworkLinks:           0,
				MaxNumberOfVirtualNetworkLinksWithReg: 100,
				NumberOfVirtualNetworkLinksWithReg:    0,
				ProvisioningState:                     "Succeeded",
			},
		}

		// Count existing record sets for this zone
		records := recordSets.Filter(func(rs RecordSet) bool {
			return strings.HasPrefix(rs.ID, resourceID+"/")
		})
		zone.Properties.NumberOfRecordSets = len(records)

		zones.Put(resourceID, zone)

		// Auto-create SOA record (azurerm provider reads this after zone creation)
		if !exists {
			soaID := fmt.Sprintf("%s/SOA/@", resourceID)
			if _, soaExists := recordSets.Get(soaID); !soaExists {
				recordSets.Put(soaID, RecordSet{
					ID:   soaID,
					Name: "@",
					Type: "Microsoft.Network/privateDnsZones/SOA",
					Etag: generateUUID(),
					Properties: RecordSetProperties{
						TTL:  3600,
						Fqdn: zoneName + ".",
						SOARecord: &SOARecord{
							Host:         "azureprivatedns.net",
							Email:        "azureprivatedns-host.microsoft.com",
							SerialNumber: 1,
							RefreshTime:  3600,
							RetryTime:    300,
							ExpireTime:   2419200,
							MinimumTTL:   300,
						},
					},
				})
				zone.Properties.NumberOfRecordSets = 1
				zones.Put(resourceID, zone)
			}
		}

		// go-azure-sdk expects 200 for sync creates
		sim.WriteJSON(w, http.StatusOK, zone)
	})

	// GET - List zones by resource group
	srv.HandleFunc("GET "+armBase+"/privateDnsZones", func(w http.ResponseWriter, r *http.Request) {
		sub := sim.PathParam(r, "subscriptionId")
		rg := sim.PathParam(r, "resourceGroupName")
		prefix := fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/", sub, rg)
		all := zones.Filter(func(z PrivateDnsZone) bool {
			return strings.HasPrefix(z.ID, prefix)
		})
		sort.Slice(all, func(i, j int) bool { return all[i].Name < all[j].Name })
		page, next := armPage(r, all)
		out := map[string]any{"value": page}
		if next != "" {
			out["nextLink"] = armNextLink(r, next)
		}
		sim.WriteJSON(w, http.StatusOK, out)
	})

	// GET - Get zone
	srv.HandleFunc("GET "+armBase+"/privateDnsZones/{zoneName}", func(w http.ResponseWriter, r *http.Request) {
		sub := sim.PathParam(r, "subscriptionId")
		rg := sim.PathParam(r, "resourceGroupName")
		zoneName := sim.PathParam(r, "zoneName")

		resourceID := fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s",
			sub, rg, zoneName)

		zone, ok := zones.Get(resourceID)
		if !ok {
			AzureErrorf(w, "ResourceNotFound", http.StatusNotFound,
				"The Resource 'Microsoft.Network/privateDnsZones/%s' under resource group '%s' was not found.", zoneName, rg)
			return
		}

		sim.WriteJSON(w, http.StatusOK, zone)
	})

	// DELETE - Delete zone
	srv.HandleFunc("DELETE "+armBase+"/privateDnsZones/{zoneName}", func(w http.ResponseWriter, r *http.Request) {
		sub := sim.PathParam(r, "subscriptionId")
		rg := sim.PathParam(r, "resourceGroupName")
		zoneName := sim.PathParam(r, "zoneName")

		resourceID := fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s",
			sub, rg, zoneName)

		if zones.Delete(resourceID) {
			// Clean up associated record sets
			records := recordSets.Filter(func(rs RecordSet) bool {
				return strings.HasPrefix(rs.ID, resourceID+"/")
			})
			for _, rs := range records {
				recordSets.Delete(rs.ID)
			}
			w.WriteHeader(http.StatusOK)
		} else {
			w.WriteHeader(http.StatusNoContent)
		}
	})

	// GET - Get SOA record
	srv.HandleFunc("GET "+armBase+"/privateDnsZones/{zoneName}/SOA/{recordName}", func(w http.ResponseWriter, r *http.Request) {
		sub := sim.PathParam(r, "subscriptionId")
		rg := sim.PathParam(r, "resourceGroupName")
		zoneName := sim.PathParam(r, "zoneName")
		recordName := sim.PathParam(r, "recordName")

		recordID := fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s/SOA/%s",
			sub, rg, zoneName, recordName)

		rs, ok := recordSets.Get(recordID)
		if !ok {
			AzureErrorf(w, "ResourceNotFound", http.StatusNotFound,
				"The record set '%s' of type 'SOA' in zone '%s' was not found.", recordName, zoneName)
			return
		}

		sim.WriteJSON(w, http.StatusOK, rs)
	})

	// PUT - Create or update A record
	srv.HandleFunc("PUT "+armBase+"/privateDnsZones/{zoneName}/A/{recordName}", func(w http.ResponseWriter, r *http.Request) {
		sub := sim.PathParam(r, "subscriptionId")
		rg := sim.PathParam(r, "resourceGroupName")
		zoneName := sim.PathParam(r, "zoneName")
		recordName := sim.PathParam(r, "recordName")

		// Verify zone exists
		zoneID := fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s",
			sub, rg, zoneName)
		if _, ok := zones.Get(zoneID); !ok {
			AzureErrorf(w, "ResourceNotFound", http.StatusNotFound,
				"The Resource 'Microsoft.Network/privateDnsZones/%s' under resource group '%s' was not found.", zoneName, rg)
			return
		}

		var req RecordSet
		if err := sim.ReadJSON(r, &req); err != nil {
			AzureError(w, "InvalidRequestContent", "Failed to parse request body: "+err.Error(), http.StatusBadRequest)
			return
		}

		recordID := fmt.Sprintf("%s/A/%s", zoneID, recordName)

		ttl := req.Properties.TTL
		if ttl == 0 {
			ttl = 3600
		}

		rs := RecordSet{
			ID:   recordID,
			Name: recordName,
			Type: "Microsoft.Network/privateDnsZones/A",
			Etag: generateUUID(),
			Properties: RecordSetProperties{
				TTL:              ttl,
				Fqdn:             recordName + "." + zoneName + ".",
				IsAutoRegistered: false,
				ARecords:         req.Properties.ARecords,
				Metadata:         req.Properties.Metadata,
			},
		}

		recordSets.Put(recordID, rs)

		// Update zone record count
		zones.Update(zoneID, func(z *PrivateDnsZone) {
			records := recordSets.Filter(func(r RecordSet) bool {
				return strings.HasPrefix(r.ID, zoneID+"/")
			})
			z.Properties.NumberOfRecordSets = len(records)
		})

		// go-azure-sdk expects 200 for sync creates
		sim.WriteJSON(w, http.StatusOK, rs)
	})

	// GET - Get A record
	srv.HandleFunc("GET "+armBase+"/privateDnsZones/{zoneName}/A/{recordName}", func(w http.ResponseWriter, r *http.Request) {
		sub := sim.PathParam(r, "subscriptionId")
		rg := sim.PathParam(r, "resourceGroupName")
		zoneName := sim.PathParam(r, "zoneName")
		recordName := sim.PathParam(r, "recordName")

		recordID := fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s/A/%s",
			sub, rg, zoneName, recordName)

		rs, ok := recordSets.Get(recordID)
		if !ok {
			AzureErrorf(w, "ResourceNotFound", http.StatusNotFound,
				"The record set '%s' of type 'A' in zone '%s' was not found.", recordName, zoneName)
			return
		}

		sim.WriteJSON(w, http.StatusOK, rs)
	})

	// DELETE - Delete A record
	srv.HandleFunc("DELETE "+armBase+"/privateDnsZones/{zoneName}/A/{recordName}", func(w http.ResponseWriter, r *http.Request) {
		sub := sim.PathParam(r, "subscriptionId")
		rg := sim.PathParam(r, "resourceGroupName")
		zoneName := sim.PathParam(r, "zoneName")
		recordName := sim.PathParam(r, "recordName")

		zoneID := fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s",
			sub, rg, zoneName)
		recordID := fmt.Sprintf("%s/A/%s", zoneID, recordName)

		if recordSets.Delete(recordID) {
			// Update zone record count
			zones.Update(zoneID, func(z *PrivateDnsZone) {
				records := recordSets.Filter(func(r RecordSet) bool {
					return strings.HasPrefix(r.ID, zoneID+"/")
				})
				z.Properties.NumberOfRecordSets = len(records)
			})
			w.WriteHeader(http.StatusOK)
		} else {
			w.WriteHeader(http.StatusNoContent)
		}
	})

	// GET - List A records
	srv.HandleFunc("GET "+armBase+"/privateDnsZones/{zoneName}/A", func(w http.ResponseWriter, r *http.Request) {
		sub := sim.PathParam(r, "subscriptionId")
		rg := sim.PathParam(r, "resourceGroupName")
		zoneName := sim.PathParam(r, "zoneName")

		prefix := fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s/A/",
			sub, rg, zoneName)

		filtered := recordSets.Filter(func(rs RecordSet) bool {
			return strings.HasPrefix(rs.ID, prefix)
		})

		sim.WriteJSON(w, http.StatusOK, map[string]any{
			"value": filtered,
		})
	})

	// CNAME / MX / TXT / AAAA / PTR / SRV record types share a generic
	// CRUD shape — the path's `recordType` segment selects which slice
	// (or singleton, in CNAME/SOA's case) of RecordSetProperties is
	// authoritative. Without these, terraform's
	// `azurerm_private_dns_{cname,mx,txt,aaaa,ptr,srv}_record` and the
	// SDK's RecordSetsClient (when called for any non-A type) hit 404.
	for _, rt := range []string{"AAAA", "CNAME", "MX", "PTR", "SRV", "TXT"} {
		recordType := rt // capture
		srv.HandleFunc(
			"PUT "+armBase+"/privateDnsZones/{zoneName}/"+recordType+"/{recordName}",
			func(w http.ResponseWriter, r *http.Request) {
				sub := sim.PathParam(r, "subscriptionId")
				rg := sim.PathParam(r, "resourceGroupName")
				zoneName := sim.PathParam(r, "zoneName")
				recordName := sim.PathParam(r, "recordName")
				zoneID := fmt.Sprintf(
					"/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s",
					sub, rg, zoneName)
				if _, ok := zones.Get(zoneID); !ok {
					AzureErrorf(w, "ResourceNotFound", http.StatusNotFound,
						"Zone %q not found in resource group %q", zoneName, rg)
					return
				}
				var req RecordSet
				if err := sim.ReadJSON(r, &req); err != nil {
					AzureError(w, "InvalidRequestContent",
						"Failed to parse request body: "+err.Error(), http.StatusBadRequest)
					return
				}
				ttl := req.Properties.TTL
				if ttl == 0 {
					ttl = 3600
				}
				recordID := fmt.Sprintf("%s/%s/%s", zoneID, recordType, recordName)
				rs := RecordSet{
					ID:   recordID,
					Name: recordName,
					Type: "Microsoft.Network/privateDnsZones/" + recordType,
					Etag: generateUUID(),
					Properties: RecordSetProperties{
						TTL:              ttl,
						Fqdn:             recordName + "." + zoneName + ".",
						IsAutoRegistered: false,
						AAAARecords:      req.Properties.AAAARecords,
						CNAMERecord:      req.Properties.CNAMERecord,
						MXRecords:        req.Properties.MXRecords,
						PTRRecords:       req.Properties.PTRRecords,
						SRVRecords:       req.Properties.SRVRecords,
						TXTRecords:       req.Properties.TXTRecords,
						Metadata:         req.Properties.Metadata,
					},
				}
				recordSets.Put(recordID, rs)
				zones.Update(zoneID, func(z *PrivateDnsZone) {
					records := recordSets.Filter(func(r RecordSet) bool {
						return strings.HasPrefix(r.ID, zoneID+"/")
					})
					z.Properties.NumberOfRecordSets = len(records)
				})
				// Realize a CNAME alias the same way the sim realizes every
				// other name: as a Docker embedded-DNS alias on the target
				// App container. A CNAME → an App's LatestRevisionFqdn means
				// recordName should resolve to that App; add it as an alias on
				// the App's env-network connection so peers resolve it.
				if recordType == "CNAME" && rs.Properties.CNAMERecord != nil {
					realizeCNAMEAsDockerAlias(rs.Properties.CNAMERecord.CName)
					realizeCNAMEAsSiteDockerAlias(rs.Properties.CNAMERecord.CName)
				}
				sim.WriteJSON(w, http.StatusOK, rs)
			})

		srv.HandleFunc(
			"GET "+armBase+"/privateDnsZones/{zoneName}/"+recordType+"/{recordName}",
			func(w http.ResponseWriter, r *http.Request) {
				sub := sim.PathParam(r, "subscriptionId")
				rg := sim.PathParam(r, "resourceGroupName")
				zoneName := sim.PathParam(r, "zoneName")
				recordName := sim.PathParam(r, "recordName")
				recordID := fmt.Sprintf(
					"/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s/%s/%s",
					sub, rg, zoneName, recordType, recordName)
				rs, ok := recordSets.Get(recordID)
				if !ok {
					AzureErrorf(w, "ResourceNotFound", http.StatusNotFound,
						"The record set '%s' of type '%s' in zone '%s' was not found.",
						recordName, recordType, zoneName)
					return
				}
				sim.WriteJSON(w, http.StatusOK, rs)
			})

		srv.HandleFunc(
			"DELETE "+armBase+"/privateDnsZones/{zoneName}/"+recordType+"/{recordName}",
			func(w http.ResponseWriter, r *http.Request) {
				sub := sim.PathParam(r, "subscriptionId")
				rg := sim.PathParam(r, "resourceGroupName")
				zoneName := sim.PathParam(r, "zoneName")
				recordName := sim.PathParam(r, "recordName")
				zoneID := fmt.Sprintf(
					"/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s",
					sub, rg, zoneName)
				recordID := fmt.Sprintf("%s/%s/%s", zoneID, recordType, recordName)
				if recordSets.Delete(recordID) {
					zones.Update(zoneID, func(z *PrivateDnsZone) {
						records := recordSets.Filter(func(r RecordSet) bool {
							return strings.HasPrefix(r.ID, zoneID+"/")
						})
						z.Properties.NumberOfRecordSets = len(records)
					})
					w.WriteHeader(http.StatusOK)
				} else {
					w.WriteHeader(http.StatusNoContent)
				}
			})

		srv.HandleFunc(
			"GET "+armBase+"/privateDnsZones/{zoneName}/"+recordType,
			func(w http.ResponseWriter, r *http.Request) {
				sub := sim.PathParam(r, "subscriptionId")
				rg := sim.PathParam(r, "resourceGroupName")
				zoneName := sim.PathParam(r, "zoneName")
				prefix := fmt.Sprintf(
					"/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s/%s/",
					sub, rg, zoneName, recordType)
				filtered := recordSets.Filter(func(rs RecordSet) bool {
					return strings.HasPrefix(rs.ID, prefix)
				})
				sim.WriteJSON(w, http.StatusOK, map[string]any{"value": filtered})
			})
	}

	vnetLinks := sim.MakeStore[VNetLink](srv.DB(), "dns_vnet_links")
	azurePrivateDNSVNetLinks = vnetLinks

	// PUT - Create or update VNet link
	srv.HandleFunc("PUT "+armBase+"/privateDnsZones/{zoneName}/virtualNetworkLinks/{linkName}", func(w http.ResponseWriter, r *http.Request) {
		sub := sim.PathParam(r, "subscriptionId")
		rg := sim.PathParam(r, "resourceGroupName")
		zoneName := sim.PathParam(r, "zoneName")
		linkName := sim.PathParam(r, "linkName")

		var req VNetLink
		if err := sim.ReadJSON(r, &req); err != nil {
			AzureError(w, "InvalidRequestContent", "Failed to parse request body", http.StatusBadRequest)
			return
		}

		resourceID := fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s/virtualNetworkLinks/%s",
			sub, rg, zoneName, linkName)

		link := VNetLink{
			ID:       resourceID,
			Name:     linkName,
			Type:     "Microsoft.Network/privateDnsZones/virtualNetworkLinks",
			Location: "global",
			Tags:     req.Tags,
			Properties: VNetLinkProperties{
				VirtualNetwork:          req.Properties.VirtualNetwork,
				RegistrationEnabled:     req.Properties.RegistrationEnabled,
				VirtualNetworkLinkState: "Completed",
				ProvisioningState:       "Succeeded",
			},
		}
		vnetLinks.Put(resourceID, link)

		// go-azure-sdk expects 200 for sync creates
		sim.WriteJSON(w, http.StatusOK, link)
	})

	// GET - List VNet links by private zone
	srv.HandleFunc("GET "+armBase+"/privateDnsZones/{zoneName}/virtualNetworkLinks", func(w http.ResponseWriter, r *http.Request) {
		sub := sim.PathParam(r, "subscriptionId")
		rg := sim.PathParam(r, "resourceGroupName")
		zoneName := sim.PathParam(r, "zoneName")
		prefix := fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s/virtualNetworkLinks/",
			sub, rg, zoneName)
		filtered := vnetLinks.Filter(func(link VNetLink) bool {
			return strings.HasPrefix(link.ID, prefix)
		})
		sim.WriteJSON(w, http.StatusOK, map[string]any{"value": filtered})
	})

	// GET - Get VNet link
	srv.HandleFunc("GET "+armBase+"/privateDnsZones/{zoneName}/virtualNetworkLinks/{linkName}", func(w http.ResponseWriter, r *http.Request) {
		sub := sim.PathParam(r, "subscriptionId")
		rg := sim.PathParam(r, "resourceGroupName")
		zoneName := sim.PathParam(r, "zoneName")
		linkName := sim.PathParam(r, "linkName")
		resourceID := fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s/virtualNetworkLinks/%s",
			sub, rg, zoneName, linkName)

		link, ok := vnetLinks.Get(resourceID)
		if !ok {
			AzureErrorf(w, "ResourceNotFound", http.StatusNotFound,
				"Virtual network link '%s' not found.", linkName)
			return
		}
		sim.WriteJSON(w, http.StatusOK, link)
	})

	// DELETE - Delete VNet link
	srv.HandleFunc("DELETE "+armBase+"/privateDnsZones/{zoneName}/virtualNetworkLinks/{linkName}", func(w http.ResponseWriter, r *http.Request) {
		sub := sim.PathParam(r, "subscriptionId")
		rg := sim.PathParam(r, "resourceGroupName")
		zoneName := sim.PathParam(r, "zoneName")
		linkName := sim.PathParam(r, "linkName")
		resourceID := fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/privateDnsZones/%s/virtualNetworkLinks/%s",
			sub, rg, zoneName, linkName)

		vnetLinks.Delete(resourceID)
		w.WriteHeader(http.StatusAccepted)
	})

	registerPrivateDNSMore(srv, zones, recordSets, vnetLinks)
}

// realizeCNAMEAsDockerAlias makes recordName resolve to the App targeted by a
// CNAME (whose value is the App's LatestRevisionFqdn) by adding it as a
// Docker embedded-DNS alias on the App's container — the same mechanism the
// sim uses to make the App name and FQDN resolve. This is how the sim
// realizes Private DNS records locally; it is not sockerless-specific (any
// CNAME → an App FQDN resolves this way). No-op when no App matches (e.g. a
// CNAME to an external target).
func realizeCNAMEAsDockerAlias(cname string) {
	target := strings.TrimSuffix(cname, ".")
	if target == "" {
		return
	}
	for _, app := range acaApps.List() {
		if strings.TrimSuffix(app.Properties.LatestRevisionFqdn, ".") != target {
			continue
		}
		envID := app.Properties.EnvironmentID
		if envID == "" {
			envID = app.Properties.ManagedEnvironmentID
		}
		env, ok := acaEnvironments.Get(envID)
		if !ok || env.DockerNetworkName == "" {
			return
		}
		handlesV, ok := acaAppReplicaHandles.Load(app.ID)
		if !ok {
			return
		}
		// Docker can't add an alias to a live network endpoint, so re-attach
		// the container with the full set: App name + FQDN + every CNAME that
		// points at this App.
		aliases := dedupeStrings(append([]string{
			app.Name,
			strings.TrimSuffix(app.Properties.LatestRevisionFqdn, "."),
		}, cnameAliasesForTarget(target)...))
		handles, _ := handlesV.([]*sim.ContainerHandle)
		for _, h := range handles {
			if h == nil || h.ContainerID == "" {
				continue
			}
			_ = sim.DisconnectContainerFromNetwork(h.ContainerID, env.DockerNetworkName)
			_ = sim.ConnectContainerToNetwork(h.ContainerID, env.DockerNetworkName, aliases)
		}
		return
	}
}

// cnameAliasesForTarget returns every CNAME record-set name pointing at the
// given target FQDN, so re-attaching a container restores all of them.
func cnameAliasesForTarget(target string) []string {
	var names []string
	for _, rs := range azurePrivateDNSRecordSets.List() {
		if rs.Properties.CNAMERecord != nil && strings.TrimSuffix(rs.Properties.CNAMERecord.CName, ".") == target {
			names = append(names, rs.Name)
		}
	}
	return names
}

func dedupeStrings(in []string) []string {
	seen := make(map[string]bool, len(in))
	var out []string
	for _, s := range in {
		if s == "" || seen[s] {
			continue
		}
		seen[s] = true
		out = append(out, s)
	}
	return out
}
