//go:build ignore

// gen-aws-error-message-members writes simulator-aws/aws_error_members_gen.go:
// for every vendored AWS Smithy model, the member name each of its error shapes
// carries its message under — `message` or `Message`, which AWS's models do not
// agree on, and which the SDKs' schema-driven deserializers read exactly.
//
// Run from the repository root:
//
//	go run scripts/gen-aws-error-message-members.go
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type shape struct {
	Type    string                     `json:"type"`
	Members map[string]json.RawMessage `json:"members"`
	Traits  map[string]json.RawMessage `json:"traits"`
}

func main() {
	models, err := filepath.Glob(filepath.Join("specs", "cloud-api", "aws", "*.smithy.json.gz"))
	if err != nil || len(models) == 0 {
		fail("no vendored AWS models under specs/cloud-api/aws: %v", err)
	}
	sort.Strings(models)
	var body strings.Builder
	for _, path := range models {
		members, err := errorMessageMembers(path)
		if err != nil {
			fail("%s: %v", path, err)
		}
		if len(members) == 0 {
			continue
		}
		model := strings.TrimSuffix(filepath.Base(path), ".smithy.json.gz")
		fmt.Fprintf(&body, "\t%q: {\n", model)
		codes := make([]string, 0, len(members))
		for code := range members {
			codes = append(codes, code)
		}
		sort.Strings(codes)
		for _, code := range codes {
			fmt.Fprintf(&body, "\t\t%q: %q,\n", code, members[code])
		}
		body.WriteString("\t},\n")
	}
	src := "// Code generated by scripts/gen-aws-error-message-members.go from the vendored\n" +
		"// Smithy models; DO NOT EDIT.\n\npackage main\n\n" +
		"// awsErrorMessageMembers is, per vendored model, the member name each error\n" +
		"// shape carries its message under.\n" +
		"var awsErrorMessageMembers = map[string]map[string]string{\n" + body.String() + "}\n"
	formatted, err := format.Source([]byte(src))
	if err != nil {
		fail("format: %v", err)
	}
	if err := os.WriteFile(filepath.Join("simulator-aws", "aws_error_members_gen.go"), formatted, 0o644); err != nil {
		fail("write: %v", err)
	}
}

// errorMessageMembers maps each error shape's name to its message member. An
// error shape with no message member is left out: it has nothing to spell.
func errorMessageMembers(path string) (map[string]string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	reader, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, err
	}
	var model struct {
		Shapes map[string]shape `json:"shapes"`
	}
	if err := json.NewDecoder(reader).Decode(&model); err != nil {
		return nil, err
	}
	out := map[string]string{}
	for id, s := range model.Shapes {
		if _, isError := s.Traits["smithy.api#error"]; !isError {
			continue
		}
		name := id[strings.LastIndex(id, "#")+1:]
		for member := range s.Members {
			if strings.EqualFold(member, "message") {
				out[name] = member
			}
		}
	}
	return out, nil
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-aws-error-message-members: "+format+"\n", args...)
	os.Exit(1)
}
