#!/usr/bin/env bash
# Generate simulator-aws/iam_resource_types_gen.go from the AWS Service
# Reference documents vendored under specs/cloud-api/aws/service-reference/.
#
# The call-time IAM gate has to answer "which resource does this request
# name?" the way AWS answers it. AWS publishes that answer — the resource
# types each action authorizes against — and it is not derivable from the
# Smithy models, which carry the aws.iam#iamAction trait for only two of the
# services the simulator serves. Hand-transcribing it would rot; generating it
# keeps the table and the vendored reference in lockstep, and
# TestIAMResourceTypesTableMatchesTheVendoredReference fails if they drift.
#
# Only services the gate can actually derive an ARN for are generated: the
# table exists to tell an extractor which resource type to build, so an entry
# with no extractor behind it would be dead weight. Adding a service here is
# deliberate and goes with the extractor that consumes it.
#
# Usage: scripts/gen-aws-iam-resource-types.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC_DIR="$ROOT/specs/cloud-api/aws/service-reference"
DEST="$ROOT/simulator-aws/iam_resource_types_gen.go"

# The IAM service prefixes iamResourceARNsForRequest can build an ARN for.
SERVICES=(acm acm-pca application-autoscaling autoscaling cloudtrail cloudwatch codebuild dynamodb ec2 ecr ecs elasticache elasticloadbalancing events firehose glue iam kinesis kms logs organizations rds secretsmanager servicediscovery sns sqs ssm states sts wafv2)

for service in "${SERVICES[@]}"; do
  if [ ! -f "$SRC_DIR/${service}.servicereference.json.gz" ]; then
    echo "error: no vendored Service Reference for $service — run scripts/fetch-aws-service-reference.sh $service" >&2
    exit 1
  fi
done

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  cat <<'EOF'
// Code generated by scripts/gen-aws-iam-resource-types.sh. DO NOT EDIT.

package main

// iamActionResourceTypes maps an IAM action to the resource types AWS
// authorizes a request for it against, as published in the AWS Service
// Reference (specs/cloud-api/aws/service-reference/). An action absent from
// this table names no resource type, which is AWS's way of saying the action
// does not support resource-level permissions — a policy for it must be
// written against "*", and the gate requests "*".
//
// Only the services iamResourceARNsForRequest builds ARNs for are generated;
// see scripts/gen-aws-iam-resource-types.sh.
var iamActionResourceTypes = map[string][]string{
EOF

  for service in "${SERVICES[@]}"; do
    gzip -dc "$SRC_DIR/${service}.servicereference.json.gz" | jq -r --arg svc "$service" '
      .Actions[]
      | select((.Resources // []) | length > 0)
      | "\t\"" + $svc + ":" + .Name + "\": {"
        + ([.Resources[].Name] | sort | map("\"" + . + "\"") | join(", "))
        + "},"
    ' | sort
  done

  echo "}"

  cat <<'EOF'

// iamResourceARNFormats maps "<service>:<resourceType>" to the ARN format AWS
// publishes for that type, verbatim from the Service Reference. The gate fills
// ${Partition}, ${Region} and ${Account} and substitutes the trailing variable
// with the identifier the request carries, which is why the whole format is
// kept rather than just the resource path: the shapes differ in ways that
// change the ARN. An Amazon Machine Image and a snapshot carry no account, the
// IPAM types carry no region, and five of Amazon EC2's types name a resource
// belonging to another service entirely (a certificate is an AWS Certificate
// Manager ARN, a role an AWS IAM one).
var iamResourceARNFormats = map[string]string{
EOF

  for service in "${SERVICES[@]}"; do
    gzip -dc "$SRC_DIR/${service}.servicereference.json.gz" | jq -r --arg svc "$service" '
      .Resources[]
      | "\t\"" + $svc + ":" + .Name + "\": \"" + .ARNFormats[0] + "\","
    ' | sort
  done

  echo "}"

  cat <<'EOF'

// iamPassRoleOperations maps an operation to the service principals AWS records
// in iam:PassedToService when the operation passes a role. AWS authorizes
// iam:PassRole on the passed role in addition to the operation's own action, so
// an operation listed here that passes a role the caller may not pass is denied
// even when the operation itself is allowed — which is the whole point of
// scoping PassRole to specific roles.
//
// Generated from every vendored Service Reference document, not only the
// services with resource derivation: PassRole is authorized against the role's
// own ARN, which the request already carries, so it needs no per-service
// extractor.
var iamPassRoleOperations = map[string][]string{
EOF

  for f in "$SRC_DIR"/*.servicereference.json.gz; do
    gzip -dc "$f" | jq -r '
      .Name as $svc
      | .Operations[]?
      | . as $op
      | (.AuthorizedActions // [])[]
      | select(.Name == "PassRole" and .Service == "iam")
      | "\t\"" + $svc + ":" + $op.Name + "\": {"
        + ((.Context["iam:PassedToService"] // []) | sort | map("\"" + . + "\"") | join(", "))
        + "},"
    ' | sort
  done

  echo "}"
} >"$tmp"

gofmt "$tmp" >"$DEST"

echo "Generated $DEST ($(grep -c '^\t"' "$DEST") actions from ${#SERVICES[@]} services)"
