//go:build ignore

// gen-aws-error-message-members writes simulator-aws/aws_error_members_gen.go:
// for every vendored AWS Smithy model, the wire name each of its error shapes
// carries its message under — `message` or `Message`, which AWS's models do not
// agree on, and which the SDKs' schema-driven deserializers read exactly — and
// the two coordinates a request names its service by: the service shape that
// prefixes an awsJson X-Amz-Target, and the SigV4 signing name.
//
// Run from the repository root:
//
//	go run scripts/gen-aws-error-message-members.go
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type member struct {
	Traits map[string]json.RawMessage `json:"traits"`
}

type shape struct {
	Type    string                     `json:"type"`
	Members map[string]member          `json:"members"`
	Traits  map[string]json.RawMessage `json:"traits"`
}

type service struct {
	model, shape, signingName string
	// errorCodeShapes lists the error shapes that carry their code in an
	// ErrorCode member, as Amazon EFS's do.
	errorCodeShapes []string
}

func main() {
	models, err := filepath.Glob(filepath.Join("specs", "cloud-api", "aws", "*.smithy.json.gz"))
	if err != nil || len(models) == 0 {
		fail("no vendored AWS models under specs/cloud-api/aws: %v", err)
	}
	sort.Strings(models)
	var body strings.Builder
	var services []service
	for _, path := range models {
		model := strings.TrimSuffix(filepath.Base(path), ".smithy.json.gz")
		members, svc, err := readModel(path)
		if err != nil {
			fail("%s: %v", path, err)
		}
		svc.model = model
		services = append(services, svc)
		if len(members) == 0 {
			continue
		}
		fmt.Fprintf(&body, "\t%q: {\n", model)
		codes := make([]string, 0, len(members))
		for code := range members {
			codes = append(codes, code)
		}
		sort.Strings(codes)
		for _, code := range codes {
			fmt.Fprintf(&body, "\t\t%q: %q,\n", code, members[code])
		}
		body.WriteString("\t},\n")
	}

	var byShape strings.Builder
	bySigning := map[string][]string{}
	for _, svc := range services {
		fmt.Fprintf(&byShape, "\t%q: %q,\n", svc.shape, svc.model)
		if svc.signingName != "" {
			bySigning[svc.signingName] = append(bySigning[svc.signingName], svc.model)
		}
	}
	signingNames := make([]string, 0, len(bySigning))
	for name := range bySigning {
		signingNames = append(signingNames, name)
	}
	sort.Strings(signingNames)
	var bySigningSrc strings.Builder
	for _, name := range signingNames {
		quoted := make([]string, 0, len(bySigning[name]))
		for _, model := range bySigning[name] {
			quoted = append(quoted, fmt.Sprintf("%q", model))
		}
		fmt.Fprintf(&bySigningSrc, "\t%q: {%s},\n", name, strings.Join(quoted, ", "))
	}

	var errorCodes strings.Builder
	for _, svc := range services {
		if len(svc.errorCodeShapes) == 0 {
			continue
		}
		sort.Strings(svc.errorCodeShapes)
		fmt.Fprintf(&errorCodes, "\t%q: {\n", svc.model)
		for _, name := range svc.errorCodeShapes {
			fmt.Fprintf(&errorCodes, "\t\t%q: true,\n", name)
		}
		errorCodes.WriteString("\t},\n")
	}

	src := "// Code generated by scripts/gen-aws-error-message-members.go from the vendored\n" +
		"// Smithy models; DO NOT EDIT.\n\npackage main\n\n" +
		"// awsErrorMessageMembers is, per vendored model, the wire name each error\n" +
		"// shape carries its message under.\n" +
		"var awsErrorMessageMembers = map[string]map[string]string{\n" + body.String() + "}\n\n" +
		"// awsModelByServiceShape maps each vendored service shape's name, which\n" +
		"// prefixes the X-Amz-Target of an awsJson request, to its model.\n" +
		"var awsModelByServiceShape = map[string]string{\n" + byShape.String() + "}\n\n" +
		"// awsModelsBySigningName maps each SigV4 signing name to the vendored models\n" +
		"// signed under it.\n" +
		"var awsModelsBySigningName = map[string][]string{\n" + bySigningSrc.String() + "}\n\n" +
		"// awsErrorCodeMembers is, per vendored model, the error shapes that carry\n" +
		"// their error code in an ErrorCode member as well as in the error type.\n" +
		"var awsErrorCodeMembers = map[string]map[string]bool{\n" + errorCodes.String() + "}\n"
	formatted, err := format.Source([]byte(src))
	if err != nil {
		fail("format: %v", err)
	}
	if err := os.WriteFile(filepath.Join("simulator-aws", "aws_error_members_gen.go"), formatted, 0o644); err != nil {
		fail("write: %v", err)
	}
}

// readModel maps each error shape's name to its message member's wire name,
// and reads the model's service shape. An error shape with no message member
// is left out: it has nothing to spell. restJson1 serializes a member under
// its smithy.api#jsonName; the awsJson protocols ignore that trait.
func readModel(path string) (map[string]string, service, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, service{}, err
	}
	reader, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, service{}, err
	}
	var model struct {
		Shapes map[string]shape `json:"shapes"`
	}
	if err := json.NewDecoder(reader).Decode(&model); err != nil {
		return nil, service{}, err
	}
	var svc service
	restJSON := false
	for id, s := range model.Shapes {
		if s.Type != "service" {
			continue
		}
		if svc.shape != "" {
			return nil, service{}, fmt.Errorf("more than one service shape")
		}
		svc.shape = id[strings.LastIndex(id, "#")+1:]
		if sigv4, ok := s.Traits["aws.auth#sigv4"]; ok {
			var trait struct {
				Name string `json:"name"`
			}
			if err := json.Unmarshal(sigv4, &trait); err != nil {
				return nil, service{}, fmt.Errorf("%s aws.auth#sigv4: %w", id, err)
			}
			svc.signingName = trait.Name
		}
		_, restJSON = s.Traits["aws.protocols#restJson1"]
	}
	if svc.shape == "" {
		return nil, service{}, fmt.Errorf("no service shape")
	}
	out := map[string]string{}
	for id, s := range model.Shapes {
		if _, isError := s.Traits["smithy.api#error"]; !isError {
			continue
		}
		name := id[strings.LastIndex(id, "#")+1:]
		if _, ok := s.Members["ErrorCode"]; ok {
			svc.errorCodeShapes = append(svc.errorCodeShapes, name)
		}
		for memberName, m := range s.Members {
			if !strings.EqualFold(memberName, "message") {
				continue
			}
			wire := memberName
			if raw, ok := m.Traits["smithy.api#jsonName"]; ok && restJSON {
				if err := json.Unmarshal(raw, &wire); err != nil {
					return nil, service{}, fmt.Errorf("%s$%s jsonName: %w", id, memberName, err)
				}
			}
			out[name] = wire
		}
	}
	return out, svc, nil
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-aws-error-message-members: "+format+"\n", args...)
	os.Exit(1)
}
