//go:build ignore

// gen-cloudwatch-cbor-shapes writes simulator-aws/cloudwatch_cbor_shapes_gen.go:
// every Amazon CloudWatch operation's input and output shape, and every shape
// they reach, reduced to the kind the rpc-v2-cbor and awsJson1_0 protocols
// encode differently. The bridge that serves an operation's CBOR surface from
// its JSON handler walks these shapes to convert timestamps, blobs and numbers.
//
// Run from the repository root:
//
//	go run scripts/gen-cloudwatch-cbor-shapes.go [output path]
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

type shape struct {
	Type    string         `json:"type"`
	Input   *ref           `json:"input"`
	Output  *ref           `json:"output"`
	Member  *ref           `json:"member"`
	Value   *ref           `json:"value"`
	Members map[string]ref `json:"members"`
}

type ref struct {
	Target string `json:"target"`
}

func main() {
	const path = "specs/cloud-api/aws/cloudwatch.smithy.json.gz"
	file, err := os.Open(path)
	if err != nil {
		fail("%v", err)
	}
	reader, err := gzip.NewReader(file)
	if err != nil {
		fail("%v", err)
	}
	var model struct {
		Shapes map[string]shape `json:"shapes"`
	}
	if err := json.NewDecoder(reader).Decode(&model); err != nil {
		fail("%s: %v", path, err)
	}

	operations := map[string][2]string{}
	reached := map[string]bool{}
	var reach func(id string)
	reach = func(id string) {
		if reached[id] {
			return
		}
		reached[id] = true
		s, ok := model.Shapes[id]
		if !ok {
			return
		}
		for _, r := range []*ref{s.Member, s.Value} {
			if r != nil {
				reach(r.Target)
			}
		}
		for _, m := range s.Members {
			reach(m.Target)
		}
	}
	for id, s := range model.Shapes {
		if s.Type != "operation" {
			continue
		}
		var io [2]string
		for i, r := range []*ref{s.Input, s.Output} {
			if r != nil && r.Target != "smithy.api#Unit" {
				io[i] = name(r.Target)
				reach(r.Target)
			}
		}
		operations[name(id)] = io
	}

	var body strings.Builder
	body.WriteString("// Code generated by scripts/gen-cloudwatch-cbor-shapes.go from specs/cloud-api/aws/cloudwatch.smithy.json.gz; DO NOT EDIT.\n\npackage main\n\n")
	body.WriteString("var cwCBOROperations = map[string]cwCBOROperation{\n")
	for _, op := range sorted(operations) {
		io := operations[op]
		fmt.Fprintf(&body, "\t%q: {Input: %q, Output: %q},\n", op, io[0], io[1])
	}
	body.WriteString("}\n\nvar cwCBORShapes = map[string]cwCBORShape{\n")
	ids := make([]string, 0, len(reached))
	for id := range reached {
		ids = append(ids, id)
	}
	sort.Slice(ids, func(i, j int) bool { return name(ids[i]) < name(ids[j]) })
	for _, id := range ids {
		kind, s := kindOf(id, model.Shapes)
		fmt.Fprintf(&body, "\t%q: {Kind: %s", name(id), kind)
		switch kind {
		case "cwCBORList":
			fmt.Fprintf(&body, ", Element: %q", name(s.Member.Target))
		case "cwCBORMap":
			fmt.Fprintf(&body, ", Element: %q", name(s.Value.Target))
		case "cwCBORStructure":
			if len(s.Members) > 0 {
				body.WriteString(", Members: map[string]string{")
				for _, m := range sorted(s.Members) {
					fmt.Fprintf(&body, "%q: %q, ", m, name(s.Members[m].Target))
				}
				body.WriteString("}")
			}
		}
		body.WriteString("},\n")
	}
	body.WriteString("}\n")

	out, err := format.Source([]byte(body.String()))
	if err != nil {
		fail("format: %v", err)
	}
	dest := "simulator-aws/cloudwatch_cbor_shapes_gen.go"
	if len(os.Args) > 1 {
		dest = os.Args[1]
	}
	if existing, err := os.ReadFile(dest); err == nil && bytes.Equal(existing, out) {
		return
	}
	if err := os.WriteFile(dest, out, 0o644); err != nil {
		fail("%v", err)
	}
}

// kindOf reduces a shape to what the two protocols encode differently.
// Smithy prelude shapes (smithy.api#Integer and the like) are not in the
// model's shape table, so their kind comes from their name.
func kindOf(id string, shapes map[string]shape) (string, shape) {
	s, ok := shapes[id]
	if !ok {
		s = shape{Type: strings.TrimPrefix(strings.TrimPrefix(id, "smithy.api#"), "Primitive")}
	}
	switch strings.ToLower(s.Type) {
	case "structure", "union":
		return "cwCBORStructure", s
	case "list", "set":
		return "cwCBORList", s
	case "map":
		return "cwCBORMap", s
	case "timestamp":
		return "cwCBORTimestamp", s
	case "blob":
		return "cwCBORBlob", s
	case "byte", "short", "integer", "long", "biginteger", "intenum":
		return "cwCBORInteger", s
	case "float", "double", "bigdecimal":
		return "cwCBORFloat", s
	default:
		return "cwCBORScalar", s
	}
}

// name keeps a CloudWatch shape's own name and a prelude shape's full ID, so
// the two cannot collide.
func name(id string) string {
	return strings.TrimPrefix(id, "com.amazonaws.cloudwatch#")
}

func sorted[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-cloudwatch-cbor-shapes: "+format+"\n", args...)
	os.Exit(1)
}
